{% set name = "arcos4py" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arcos4py-{{ version }}.tar.gz
  sha256: e53ecba20da89c35ff046126e0ed0bbe649e84feae01050da2409dbc6085c761

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - joblib >=1.3.0
    - kneed >=0.7.0
    - matplotlib-base >=3.3.4
    - numpy >=1.23
    - pandas >=1.4.0
    - pot >=0.9.4
    - numba >=0.60.0
    - python >={{ python_min }}
    - scikit-image >=0.21.0
    - scikit-learn >=1.3.0
    - scipy >=1.9
    - seaborn >=0.11.2
    - tqdm >=4.64.1

test:
  imports:
    - arcos4py
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/arcos4py
  summary: A python package to detect collective spatio-temporal phenomena.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/bgraedel/arcos4py

extra:
  recipe-maintainers:
    - bgraedel
    - goanpeca
