{% set name = "arcos4py" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arcos4py-{{ version }}.tar.gz
  sha256: 92aad97265cec3ab1418189370a0ccb5e8a73555f42af02ab197b3317c56d6bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.8,<3.12
  run:
    - joblib >=1.2.0
    - kneed >=0.7.0
    - matplotlib-base >=3.3.4
    - mkdocs-material-extensions >=1.0.3,<2.0.0
    - numpy >=1.21.6
    - pandas >=1.3.5
    - pulp >=2.7.0,<3.0.0
    - python >=3.8,<3.12
    - scikit-image >=0.21.0,<0.22.0
    - scikit-learn >=1.3.0
    - scipy >=1.7.3
    - seaborn >=0.11.2,<0.12.0
    - tqdm >=4.64.1

test:
  imports:
    - arcos4py
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bgraedel/arcos4py
  summary: A python package to detect collective spatio-temporal phenomena.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/bgraedel/arcos4py

extra:
  recipe-maintainers:
    - bgraedel
    - goanpeca
