{% set name = "arcos4py" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arcos4py-{{ version }}.tar.gz
  sha256: 24ef6e44b12f2a9067343a77941117990eb86b0a038b324b70505380f0fe0afb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.8
  run:
    - matplotlib-base >=3.3.4
    - mkdocs-material-extensions >=1.0.3,<2.0.0
    - numpy >=1.21.5
    - pandas >=1.3.5
    - python >=3.8
    - scikit-learn >=1.0.2
    - scipy >=1.7.3
    - seaborn >=0.11.2,<0.12.0

test:
  imports:
    - arcos4py
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bgraedel/arcos4py
  summary: A python package to detect collective spatio-temporal phenomena.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgraedel
    - goanpeca
